# Generated by Django 4.2 on 2023-05-04 16:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_article_options_alter_article_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 250 сим.', max_length=250, verbose_name='Інформація')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('slug', models.SlugField(unique_for_date='pub_date', verbose_name='Слаг')),
                ('main_page', models.BooleanField(default=True, help_text='Показувати на головній сторінці', verbose_name='Головна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles1', to='app_blog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Додаткова інформація',
                'verbose_name_plural': 'Додаткові інформації',
                'ordering': ['-pub_date'],
            },
        ),
        migrations.CreateModel(
            name='ArticleImage1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos', verbose_name='Фото')),
                ('title', models.CharField(blank=True, help_text='Максимум 250 сим.', max_length=250, verbose_name='Заголовок')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_blog.article1', verbose_name='Додаткова інформація')),
            ],
            options={
                'verbose_name': 'Фото для інформації',
                'verbose_name_plural': 'Фото для інформації',
            },
        ),
    ]
