# Generated by Django 4.2 on 2023-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_article1_articleimage1'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article1',
            options={'ordering': ['-pub_date'], 'verbose_name': 'Додаткова інформація', 'verbose_name_plural': 'Додаткова інформація'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(help_text='Максимум 250 сим.', max_length=250, verbose_name='Категорія'),
        ),
    ]
